In [55]:
import pandas as pd
import numpy as np

In [56]:
!ls ./01.functional_traits

41559_2019_1070_MOESM3_ESM.csv	AVONET_Raw_Data.csv  Innovativeness.csv
AVONET1_BirdLife.csv		Brain_size.csv

In [57]:
raw_data = pd.read_csv('./01.functional_traits/AVONET_Raw_Data.csv')
raw_data.columns

Index(['Avibase.ID', 'Species1_BirdLife', 'Species2_eBird',
       'eBird.species.group', 'Species3_BirdTree', 'Data.type', 'Source',
       'Specimen.number', 'Sex', 'Age', 'Locality', 'Country_WRI', 'Country',
       'Beak.Length_Culmen', 'Beak.Length_Nares', 'Beak.Width', 'Beak.Depth',
       'Tarsus.Length', 'Wing.Length', 'Kipps.Distance', 'Secondary1',
       'Hand-wing.Index', 'Tail.Length', 'Measurer', 'Protocol',
       'Publication'],
      dtype='object')

In [58]:
raw_data = raw_data.groupby(['Species1_BirdLife', 'Species2_eBird',
       'eBird.species.group', 'Species3_BirdTree']).first().reset_index(drop=False)[['Species1_BirdLife', 'Species2_eBird',
       'eBird.species.group', 'Species3_BirdTree']]

In [59]:
raw_data

,Species1_BirdLife,Species2_eBird,eBird.species.group,Species3_BirdTree
0,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei,Abeillia abeillei
1,Abroscopus albogularis,Abroscopus albogularis,Abroscopus albogularis,Abroscopus albogularis
2,Abroscopus schisticeps,Abroscopus schisticeps,Abroscopus schisticeps,Abroscopus schisticeps
3,Abroscopus superciliaris,Abroscopus superciliaris,Abroscopus superciliaris,Abroscopus superciliaris
4,Aburria aburri,Aburria aburri,Aburria aburri,Aburria aburri
...,...,...,...,...
11223,Zosterornis hypogrammicus,Zosterornis hypogrammicus,Zosterornis hypogrammicus,Stachyris hypogrammica
11224,Zosterornis latistriatus,Zosterornis latistriatus,Zosterornis latistriatus,Stachyris latistriata
11225,Zosterornis nigrorum,Zosterornis nigrorum,Zosterornis nigrorum,Stachyris nigrorum
11226,Zosterornis striatus,Zosterornis striatus,Zosterornis striatus,Stachyris striata
11227,Zosterornis whiteheadi,Zosterornis whiteheadi,Zosterornis whiteheadi,Stachyris whiteheadi

In [60]:
file_path = "./01.functional_traits/41559_2019_1070_MOESM3_ESM.csv"
functional_data = pd.read_csv(file_path)
functional_data['Binomial'] = [i.replace("_",' ') for i in functional_data['Binomial'].values]

In [61]:
functional_data

,Binomial,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,Beak_PC1,Beak_PC2,Beak_PC3,Beak_PC4,Realm,TrophicLevel,TrophicNiche,ForagingNiche,Unnamed: 18
0,Abeillia abeillei,-4.147189,-0.486052,0.717944,-0.500533,-0.443798,-0.087093,-0.469909,-0.321176,-0.075071,-1.860983,0.987627,-0.409249,0.165534,Neotropic,Herbivore,Nectarivore,Nectarivore aerial,NaN
1,Abroscopus albogularis,-3.120945,0.324101,-0.159079,-0.043106,0.275685,-0.059945,0.174917,-0.088514,0.035767,-1.717089,-0.121699,0.149836,-0.047662,Indo_Malay,Carnivore,Invertivore,Invertivore glean arboreal,NaN
2,Abroscopus schisticeps,-3.149218,0.422666,-0.215050,-0.107048,0.293913,-0.027429,0.102600,-0.075941,0.012848,-1.817145,-0.139674,0.080107,-0.023306,Indo_Malay,Carnivore,Invertivore,Invertivore glean arboreal,NaN
3,Abroscopus superciliaris,-2.608415,-0.006795,-0.020313,-0.029840,0.283499,0.088849,0.116898,0.008324,0.000294,-1.221007,0.057480,0.104714,0.036213,Indo_Malay,Carnivore,Invertivore,Invertivore glean arboreal,NaN
4,Aburria aburri,4.039849,1.154168,-0.152762,-0.508404,-0.203768,-0.157020,0.116998,0.208262,0.006971,0.891460,-0.127496,0.084316,-0.234310,Neotropic,Herbivore,Frugivore,Fugivore glean,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9958,Zosterops uropygialis,-1.733895,0.120182,0.024530,0.051994,0.211733,-0.046553,-0.068965,0.012155,0.019916,-0.900498,-0.025302,-0.090667,-0.010679,Australian,Omnivore,Omnivore,NaN,NaN
9959,Zosterops vaughani,-2.645781,0.062789,0.025910,0.093602,0.165836,0.081824,0.015772,0.033386,0.004510,-1.296084,-0.017197,0.009939,0.036992,Afrotropic,Herbivore,Frugivore,Fugivore glean,NaN
9960,Zosterops vellalavella,-1.972674,-0.087005,0.091340,-0.078696,0.199551,0.132439,-0.042382,0.083759,0.053426,-0.882405,0.181320,-0.052074,-0.000347,Australian,Omnivore,Omnivore,NaN,NaN
9961,Zosterops wallacei,-2.137061,0.114831,0.158139,0.084049,0.180943,0.001673,-0.041606,0.070305,0.041221,-1.108439,0.052396,-0.063366,-0.027432,Australian,Omnivore,Omnivore,NaN,NaN
9962,Zosterops xanthochroa,-2.055791,0.103217,0.048689,-0.130438,0.269317,0.024677,-0.070518,-0.012906,0.034772,-1.070404,0.124881,-0.090556,-0.018096,Australian,Omnivore,Invertivore,Invertivore glean arboreal,NaN

In [62]:
functional_data = functional_data[['Binomial','PC1','PC2','PC3','PC4','PC5','PC6','PC7','PC8','PC9',
                                   'Beak_PC1','Beak_PC2','Beak_PC3','Beak_PC4',
                                   
             'TrophicLevel','TrophicNiche','ForagingNiche']].rename(columns={
    'Binomial':'species'
})
functional_data.head()

,species,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,Beak_PC1,Beak_PC2,Beak_PC3,Beak_PC4,TrophicLevel,TrophicNiche,ForagingNiche
0,Abeillia abeillei,-4.147189,-0.486052,0.717944,-0.500533,-0.443798,-0.087093,-0.469909,-0.321176,-0.075071,-1.860983,0.987627,-0.409249,0.165534,Herbivore,Nectarivore,Nectarivore aerial
1,Abroscopus albogularis,-3.120945,0.324101,-0.159079,-0.043106,0.275685,-0.059945,0.174917,-0.088514,0.035767,-1.717089,-0.121699,0.149836,-0.047662,Carnivore,Invertivore,Invertivore glean arboreal
2,Abroscopus schisticeps,-3.149218,0.422666,-0.215050,-0.107048,0.293913,-0.027429,0.102600,-0.075941,0.012848,-1.817145,-0.139674,0.080107,-0.023306,Carnivore,Invertivore,Invertivore glean arboreal
3,Abroscopus superciliaris,-2.608415,-0.006795,-0.020313,-0.029840,0.283499,0.088849,0.116898,0.008324,0.000294,-1.221007,0.057480,0.104714,0.036213,Carnivore,Invertivore,Invertivore glean arboreal
4,Aburria aburri,4.039849,1.154168,-0.152762,-0.508404,-0.203768,-0.157020,0.116998,0.208262,0.006971,0.891460,-0.127496,0.084316,-0.234310,Herbivore,Frugivore,Fugivore glean

In [63]:
ebird_name = pd.read_csv('./03.ebird_name/eBird_Taxonomy_v2021.csv')
ebird_name = ebird_name[ebird_name['CATEGORY']=='species']
ebird_name = ebird_name[['PRIMARY_COM_NAME','SCI_NAME','ORDER1','FAMILY']].rename(columns={
    'SCI_NAME':'species',
    'PRIMARY_COM_NAME':'common_name',
    'ORDER1':'order',
    'FAMILY':'family'
})
ebird_name.head()

,common_name,species,order,family
0,Common Ostrich,Struthio camelus,Struthioniformes,Struthionidae (Ostriches)
1,Somali Ostrich,Struthio molybdophanes,Struthioniformes,Struthionidae (Ostriches)
3,Greater Rhea,Rhea americana,Rheiformes,Rheidae (Rheas)
4,Lesser Rhea,Rhea pennata,Rheiformes,Rheidae (Rheas)
7,Tawny-breasted Tinamou,Nothocercus julius,Tinamiformes,Tinamidae (Tinamous)

In [76]:
birdlife_data = pd.read_csv('./01.functional_traits/AVONET1_BirdLife.csv')
birdlife_data = birdlife_data[['Species1','Beak.Length_Culmen', 'Beak.Length_Nares', 'Beak.Width', 'Beak.Depth',
       'Tarsus.Length', 'Wing.Length', 'Kipps.Distance', 'Secondary1',
       'Hand-Wing.Index', 'Tail.Length', 'Mass','Habitat', 'Habitat.Density', 'Migration',
                              'Primary.Lifestyle','Range.Size']].rename(columns={
    'Species1':'Species1_BirdLife'
})


birdlife_data.head()

,Species1_BirdLife,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Habitat,Habitat.Density,Migration,Primary.Lifestyle,Range.Size
0,Accipiter albogularis,27.7,17.8,10.6,14.7,62.0,235.2,81.8,159.5,33.9,169.0,248.8,Forest,1,2.0,Insessorial,37461.21
1,Accipiter badius,20.6,12.1,8.8,11.6,43.0,186.7,62.5,127.4,32.9,140.6,131.2,Shrubland,2,3.0,Insessorial,22374973.00
2,Accipiter bicolor,25.0,13.7,8.6,12.7,58.1,229.6,56.6,174.8,24.6,186.3,287.5,Woodland,2,2.0,Generalist,14309701.27
3,Accipiter brachyurus,22.5,14.0,8.9,11.9,61.2,202.2,64.1,138.1,31.7,140.8,142.0,Forest,1,2.0,Insessorial,35580.71
4,Accipiter brevipes,21.1,12.1,8.7,11.1,46.4,217.6,87.8,129.9,40.2,153.5,186.5,Forest,1,3.0,Generalist,2936751.80

In [98]:
inno = pd.read_csv('./01.functional_traits/Innovativeness.csv')
inno = inno[['Species','TotalInnovations', 'TotalFoodTypeInnovations',
       'TotalTechnicalInnovations', 'InnovationYesOrNo',
       'FoodTypeInnovationYesOrNo', 'TechnicalInnovationYesOrNo']]
inno['Species'] = [" ".join(i.split("_")) for i in inno.Species.values]
inno = inno.rename(columns={'Species':'Species1_BirdLife'})
inno.columns

Index(['Species1_BirdLife', 'TotalInnovations', 'TotalFoodTypeInnovations',
       'TotalTechnicalInnovations', 'InnovationYesOrNo',
       'FoodTypeInnovationYesOrNo', 'TechnicalInnovationYesOrNo'],
      dtype='object')

In [106]:
brain_size = pd.read_csv('./01.functional_traits/Brain_size.csv')\
    [['Species','BrainSize','RelativeBrainSize']].rename(columns={'Species':'Species1_BirdLife'})

brain_size['Species1_BirdLife'] = [" ".join(i.split("_")) for i in brain_size['Species1_BirdLife'].values]

In [107]:
brain_size

             Species1_BirdLife  BrainSize  RelativeBrainSize
0       Abroscopus albogularis       0.32              0.251
1     Acanthagenys rufogularis       1.16              0.273
2        Acanthiza chrysorrhoa       0.43              0.192
3            Acanthiza ewingii       0.63              1.053
4           Acanthiza inornata       0.44              0.272
...                        ...        ...                ...
1926           Zoothera heinei       1.80              0.475
1927         Zoothera lunulata       2.16              0.458
1928           Zoothera naevia       1.71              0.389
1929       Zosterops japonicus       0.54              0.375
1930       Zosterops lateralis       0.47              0.070

[1931 rows x 3 columns]

In [108]:
#### merge
merged = pd.merge(
    pd.merge(
        pd.merge(ebird_name, raw_data, left_on='species',right_on='Species2_eBird',how='left'), 
        birdlife_data, left_on='Species1_BirdLife', right_on = 'Species1_BirdLife', how='left'
    ),
    functional_data, on='species',how='left'
)

merged = pd.merge(
    pd.merge(merged,
                 inno,on='Species1_BirdLife', how='left'),
    brain_size, on='Species1_BirdLife', how='left'
)


merged.head()

,common_name,species,order,family,Species1_BirdLife,Species2_eBird,eBird.species.group,Species3_BirdTree,Beak.Length_Culmen,Beak.Length_Nares,...,TrophicNiche,ForagingNiche,TotalInnovations,TotalFoodTypeInnovations,TotalTechnicalInnovations,InnovationYesOrNo,FoodTypeInnovationYesOrNo,TechnicalInnovationYesOrNo,BrainSize,RelativeBrainSize
0,Common Ostrich,Struthio camelus,Struthioniformes,Struthionidae (Ostriches),Struthio camelus,Struthio camelus,Struthio camelus,Struthio camelus,90.5,51.2,...,Omnivore,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,Somali Ostrich,Struthio molybdophanes,Struthioniformes,Struthionidae (Ostriches),Struthio molybdophanes,Struthio molybdophanes,Struthio molybdophanes,Struthio camelus,89.2,52.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,Greater Rhea,Rhea americana,Rheiformes,Rheidae (Rheas),Rhea americana,Rhea americana,Rhea americana,Rhea americana,86.5,35.6,...,Omnivore,NaN,1.0,1.0,0.0,1.0,1.0,0.0,18.88,-0.401
3,Lesser Rhea,Rhea pennata,Rheiformes,Rheidae (Rheas),Rhea pennata,Rhea pennata,Rhea pennata pennata,Rhea pennata,68.6,33.1,...,Omnivore,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,Lesser Rhea,Rhea pennata,Rheiformes,Rheidae (Rheas),Rhea tarapacensis,Rhea pennata,Rhea pennata tarapacensis/garleppi,Rhea pennata,75.6,35.0,...,Omnivore,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [109]:
merged.isnull().sum()

common_name                      0
species                          0
order                            0
family                           0
Species1_BirdLife              330
Species2_eBird                 330
eBird.species.group            330
Species3_BirdTree              330
Beak.Length_Culmen             341
Beak.Length_Nares              341
Beak.Width                     341
Beak.Depth                     341
Tarsus.Length                  341
Wing.Length                    341
Kipps.Distance                 341
Secondary1                     341
Hand-Wing.Index                341
Tail.Length                    341
Mass                           341
Habitat                        410
Habitat.Density                341
Migration                      357
Primary.Lifestyle              341
Range.Size                     384
PC1                           2985
PC2                           2985
PC3                           2985
PC4                           2985
PC5                           2985
PC6                           2985
PC7                           2985
PC8                           2985
PC9                           2985
Beak_PC1                      2985
Beak_PC2                      2985
Beak_PC3                      2985
Beak_PC4                      2985
TrophicLevel                  2985
TrophicNiche                  2985
ForagingNiche                 4491
TotalInnovations              2792
TotalFoodTypeInnovations      2792
TotalTechnicalInnovations     2792
InnovationYesOrNo             2792
FoodTypeInnovationYesOrNo     2792
TechnicalInnovationYesOrNo    2792
BrainSize                     9824
RelativeBrainSize             9824
dtype: int64

In [110]:
merged.to_csv('functional_trophical_foraging_data.csv',index=False)

In [111]:
merged = pd.read_csv('functional_trophical_foraging_data.csv')
merged.head()

,common_name,species,order,family,Species1_BirdLife,Species2_eBird,eBird.species.group,Species3_BirdTree,Beak.Length_Culmen,Beak.Length_Nares,...,TrophicNiche,ForagingNiche,TotalInnovations,TotalFoodTypeInnovations,TotalTechnicalInnovations,InnovationYesOrNo,FoodTypeInnovationYesOrNo,TechnicalInnovationYesOrNo,BrainSize,RelativeBrainSize
0,Common Ostrich,Struthio camelus,Struthioniformes,Struthionidae (Ostriches),Struthio camelus,Struthio camelus,Struthio camelus,Struthio camelus,90.5,51.2,...,Omnivore,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,Somali Ostrich,Struthio molybdophanes,Struthioniformes,Struthionidae (Ostriches),Struthio molybdophanes,Struthio molybdophanes,Struthio molybdophanes,Struthio camelus,89.2,52.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,Greater Rhea,Rhea americana,Rheiformes,Rheidae (Rheas),Rhea americana,Rhea americana,Rhea americana,Rhea americana,86.5,35.6,...,Omnivore,NaN,1.0,1.0,0.0,1.0,1.0,0.0,18.88,-0.401
3,Lesser Rhea,Rhea pennata,Rheiformes,Rheidae (Rheas),Rhea pennata,Rhea pennata,Rhea pennata pennata,Rhea pennata,68.6,33.1,...,Omnivore,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,Lesser Rhea,Rhea pennata,Rheiformes,Rheidae (Rheas),Rhea tarapacensis,Rhea pennata,Rhea pennata tarapacensis/garleppi,Rhea pennata,75.6,35.0,...,Omnivore,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [112]:
len(merged.common_name.unique()),\
len(merged)

(10824, 11551)